//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ISU/", ConfigurationName="ServiceReference1.ISUSMS")]
    public interface ISUSMS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ISU/ISUSMS/sendSMSISURequest", ReplyAction="http://ISU/ISUSMS/sendSMSISUResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FinalProject3.ServiceReference1.sendSMSISUResponse sendSMSISU(FinalProject3.ServiceReference1.sendSMSISURequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ISU/ISUSMS/sendSMSRequest", ReplyAction="http://ISU/ISUSMS/sendSMSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FinalProject3.ServiceReference1.sendSMSResponse sendSMS(FinalProject3.ServiceReference1.sendSMSRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ISU/ISUSMS/getCarriersRequest", ReplyAction="http://ISU/ISUSMS/getCarriersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FinalProject3.ServiceReference1.getCarriersResponse getCarriers(FinalProject3.ServiceReference1.getCarriersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSISU", WrapperNamespace="http://ISU/", IsWrapped=true)]
    public partial class sendSMSISURequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ISU/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ISU/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ISU/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string provider;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ISU/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ISU/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message;
        
        public sendSMSISURequest() {
        }
        
        public sendSMSISURequest(string username, string password, string provider, string number, string message) {
            this.username = username;
            this.password = password;
            this.provider = provider;
            this.number = number;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSISUResponse", WrapperNamespace="http://ISU/", IsWrapped=true)]
    public partial class sendSMSISUResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ISU/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sendSMSISUResponse() {
        }
        
        public sendSMSISUResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMS", WrapperNamespace="http://ISU/", IsWrapped=true)]
    public partial class sendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ISU/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string provider;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ISU/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ISU/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message;
        
        public sendSMSRequest() {
        }
        
        public sendSMSRequest(string provider, string number, string message) {
            this.provider = provider;
            this.number = number;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSResponse", WrapperNamespace="http://ISU/", IsWrapped=true)]
    public partial class sendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ISU/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sendSMSResponse() {
        }
        
        public sendSMSResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCarriers", WrapperNamespace="http://ISU/", IsWrapped=true)]
    public partial class getCarriersRequest {
        
        public getCarriersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCarriersResponse", WrapperNamespace="http://ISU/", IsWrapped=true)]
    public partial class getCarriersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ISU/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getCarriersResponse() {
        }
        
        public getCarriersResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISUSMSChannel : FinalProject3.ServiceReference1.ISUSMS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SUSMSClient : System.ServiceModel.ClientBase<FinalProject3.ServiceReference1.ISUSMS>, FinalProject3.ServiceReference1.ISUSMS {
        
        public SUSMSClient() {
        }
        
        public SUSMSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SUSMSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SUSMSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SUSMSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinalProject3.ServiceReference1.sendSMSISUResponse FinalProject3.ServiceReference1.ISUSMS.sendSMSISU(FinalProject3.ServiceReference1.sendSMSISURequest request) {
            return base.Channel.sendSMSISU(request);
        }
        
        public string sendSMSISU(string username, string password, string provider, string number, string message) {
            FinalProject3.ServiceReference1.sendSMSISURequest inValue = new FinalProject3.ServiceReference1.sendSMSISURequest();
            inValue.username = username;
            inValue.password = password;
            inValue.provider = provider;
            inValue.number = number;
            inValue.message = message;
            FinalProject3.ServiceReference1.sendSMSISUResponse retVal = ((FinalProject3.ServiceReference1.ISUSMS)(this)).sendSMSISU(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinalProject3.ServiceReference1.sendSMSResponse FinalProject3.ServiceReference1.ISUSMS.sendSMS(FinalProject3.ServiceReference1.sendSMSRequest request) {
            return base.Channel.sendSMS(request);
        }
        
        public string sendSMS(string provider, string number, string message) {
            FinalProject3.ServiceReference1.sendSMSRequest inValue = new FinalProject3.ServiceReference1.sendSMSRequest();
            inValue.provider = provider;
            inValue.number = number;
            inValue.message = message;
            FinalProject3.ServiceReference1.sendSMSResponse retVal = ((FinalProject3.ServiceReference1.ISUSMS)(this)).sendSMS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinalProject3.ServiceReference1.getCarriersResponse FinalProject3.ServiceReference1.ISUSMS.getCarriers(FinalProject3.ServiceReference1.getCarriersRequest request) {
            return base.Channel.getCarriers(request);
        }
        
        public string[] getCarriers() {
            FinalProject3.ServiceReference1.getCarriersRequest inValue = new FinalProject3.ServiceReference1.getCarriersRequest();
            FinalProject3.ServiceReference1.getCarriersResponse retVal = ((FinalProject3.ServiceReference1.ISUSMS)(this)).getCarriers(inValue);
            return retVal.@return;
        }
    }
}
